New careers
Naturaily/Naturaily-netlify pull request #1057
Opened 2021-08-10 13:27 UTC by galdranorn

2021-08-17 12:55 UTC, siaradona requested changes

2021-08-17 12:55 UTC, siaradona commented on _includes/careers/hero.js
> +      return;
`return showVideo();` (?)

2021-08-17 12:55 UTC, siaradona commented on _includes/careers/hero.js
> +function onYouTubeIframeAPIReady() {
arrow?

2021-08-17 12:55 UTC, siaradona commented on _includes/careers/path.html
> +    <img src="/assets/images/loader.gif" data-src="/assets/images/careers/path.webp" />
alt

2021-08-17 12:55 UTC, siaradona commented on _includes/slider.js
> +  }
```
const incredibleName = {
  default: 'services-slider_card--opened'
  'product-desing': 'product-design__accordion-card--opened',
  'careers': 'careers-organization__card--opened',
  [...]
}

const openCardClass = incredibleName[sliderType]
```

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_atmosphere.scss
> +        background-image: linear-gradient(0deg, $color-secondary 0%, $color-secondary 50%, $color-home-grey 50%, $color-home-grey 100%);
```
background-image: linear-gradient(0deg, $color-secondary 0%,
                                        $color-secondary 50%,
                                        $color-home-grey 50%,
                                        $color-home-grey 100%); 

```

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_atmosphere.scss
> +
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_cta.scss
> +      margin-bottom: 15px;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_hero.scss
> +    background: linear-gradient(270deg, $color-secondary 0%, $color-secondary 50%, $color-white 0%, $color-white 100%);
..

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_hero.scss
> +      padding-top: 0;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_hero.scss
> +        width: 130px;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_involvement.scss
> +      background: linear-gradient(270deg, $color-secondary 0%, $color-secondary 50%, $color-white 0%, $color-white 100%);
..

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_organization.scss
> +        background: $color-white;
background-color

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_path.scss
> +      background: linear-gradient(270deg, $color-secondary 0%, $color-secondary 50%, $color-white 0%, $color-white 100%);
..

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_recruitment.scss
> +    background: $color-geometric-blue-accent;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_recruitment.scss
> +      background: $color-accent-yellow;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_recruitment.scss
> +        background: $color-secondary;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_recruitment.scss
> +        background-image: linear-gradient(0deg, $color-secondary 0%, $color-secondary 50%, $color-white 50%, $color-white 100%);
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_blog.scss
> +  background: $color-page-text;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_blog.scss
> +
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_blog.scss
> +    background: linear-gradient(270deg, $color-page-text 50%, $color-white 0%, $color-white 100%);
..

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_openings.scss
> +      background: $color-white;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_openings.scss
> +        background: $color-accent-yellow;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_openings.scss
> +        background: $color-estimate-dot-green;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_openings.scss
> +        background: $color-geometric-blue;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_openings.scss
> +      background: linear-gradient(270deg, $color-white 0%, $color-white 50%, $color-secondary 0%, $color-secondary 100%);
..

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_openings.scss
> +      transition: .2s;
`transition: all .2s` or `transition-duration: .2s`

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_openings.scss
> +      transition: .2s;
.

2021-08-17 12:55 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_atmosphere.scss
> +        transition: color .2s, background-position .2s;
all (?)

2021-08-17 12:55 UTC, siaradona commented on _includes/careers/organization.html
> +              <img src="/assets/images/loader.gif" data-src="{{ perk.img }}" />
alt

2021-08-17 13:03 UTC, galdranorn commented on _includes/careers/hero.js
> +function onYouTubeIframeAPIReady() {
this one function is not working this way

2021-08-17 15:52 UTC, galdranorn commented on _sass/new-styles/modules/careers/careers/_atmosphere.scss
> +        background-image: linear-gradient(0deg, $color-secondary 0%, $color-secondary 50%, $color-home-grey 50%, $color-home-grey 100%);
+ moved to _buttons.scss

2021-08-17 16:11 UTC, galdranorn commented on _sass/new-styles/modules/careers/careers/_recruitment.scss
> +        background-image: linear-gradient(0deg, $color-secondary 0%, $color-secondary 50%, $color-white 50%, $color-white 100%);
and moved to _buttons.scss

2021-08-18 07:25 UTC, siaradona requested changes

2021-08-18 07:25 UTC, siaradona commented on _includes/slider.js
> +  const openCardClass = openClasses[$slider[0].dataset.type];
`const openCardClass = openClasses[sliderType];`

2021-08-18 07:25 UTC, siaradona commented on _sass/buttons.scss
> +                                            $color-white 100%);
Why 50% is before 0%?

2021-08-18 07:25 UTC, siaradona commented on _sass/new-styles/modules/careers/careers/_involvement.scss
> +    position: relative;
.

2021-08-18 07:25 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_blog.scss
> +      left: 0;
.

2021-08-18 07:25 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_blog.scss
> +      position: relative;
.

2021-08-18 07:25 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_blog.scss
> +        position: relative;
.

2021-08-18 07:25 UTC, siaradona commented on _sass/new-styles/modules/careers/offers/_openings.scss
> +      bottom: 0;
.

2021-08-18 07:32 UTC, galdranorn commented on _sass/buttons.scss
> +                                            $color-white 100%);
to make "hard" not "smooth" transition between colors

2021-08-18 07:44 UTC, siaradona approved these changes

2021-08-18 07:45 UTC, merged